package org.komponente.userservice.exceptions;

public enum ErrorCode {
    RESOURCE_NOT_FOUND, EMAIL_ALREADY_IN_USE, USERNAME_ALREADY_IN_USE, REVOKE_ADMIN_ERROR,
    ALREADY_REVOKED, ALREADY_CAN_USE, RANK_NAME_ERROR, NO_ACCESS
}
